import { PreviewScenario, PreviewScenarioKey } from "./types";

export const PREVIEW_SCENARIOS: Record<PreviewScenarioKey, PreviewScenario> = {
    preflight_match: {
        key: "preflight_match",
        label: "Preflight Match",
        description: "Happy path. All overview cards match before departure.",
        defaultSection: "overview",
        status: {
            simconnect_connected: true,
            current_aircraft: "C172SP G1000 Cargo",
            current_airport: "LTFM",
            airport_match: true,
            aircraft_match: true,
            payload_match: true,
            flight_state: "",
            flight_progress: [],
            parked_label: "Parked at LTFM",
            sim_utc_hour: 9,
            sim_utc_minute: 42,
            active_sim_state_label: "On Ground",
        },
        simconnect: {
            statusText: "SimConnect: Connected",
            statusTone: "success",
            aircraftLine: "Aircraft: C172SP G1000 Cargo",
            airportLine: "Airport: LTFM",
            gameModeLine: "GameMode: CAREER",
            menuLine: "IsInMenu: false",
            postLine: "EFB POST: OK",
            connectionLine: "SimConnect timing: 2 seconds passed",
        },
        payload: {
            summary: "Payload 582 / 870 lbs | Fuel 318 lbs | Estimated TOW 2,264 / 2,550 lbs",
            plannerPercent: 65,
            plannerDetail: "Planner 65% -> target payload 566 lbs | pax 2 | cargo 226 lbs | est TOW 2,248 / 2,550 lbs",
            cargoRows: [
                { name: "Cargo 3 (Rear hold)", current: "126 lbs", max: "200 lbs" },
                { name: "Cargo 4 (Nose bay)", current: "100 lbs", max: "150 lbs" },
            ],
            baggageRows: [
                { name: "Baggage 5 (Aft shelf)", current: "36 lbs", max: "120 lbs" },
            ],
            seatSummary: "Passenger-loadable seats: 3 | Occupied pax: 2",
            seatRows: [
                { name: "Row 1", current: "1 pax", max: "1 pax" },
                { name: "Row 2", current: "1 pax", max: "2 pax" },
            ],
            resultText: "Preview mode: no writeback, visual validation only.",
            resultTone: "info",
        },
    },
    preflight_mismatch: {
        key: "preflight_mismatch",
        label: "Preflight Mismatch",
        description: "Mixed validation states to check card contrast and text density.",
        defaultSection: "overview",
        status: {
            simconnect_connected: true,
            current_aircraft: "Cessna Citation CJ4",
            current_airport: "LOWI",
            airport_match: false,
            aircraft_match: true,
            payload_match: false,
            required_airport: "LIMC",
            required_payload_lbs: 1400,
            flight_state: "",
            flight_progress: [],
            parked_label: "Parked at LOWI",
            sim_utc_hour: 16,
            sim_utc_minute: 5,
            active_sim_state_label: "Ground Ready",
        },
        simconnect: {
            statusText: "SimConnect: Connected",
            statusTone: "success",
            aircraftLine: "Aircraft: Cessna Citation CJ4",
            airportLine: "Airport: LOWI",
            gameModeLine: "GameMode: FREE FLIGHT",
            menuLine: "IsInMenu: false",
            postLine: "EFB POST: accepted_new_session",
            connectionLine: "SimConnect timing: connected (waiting 2s)",
        },
        payload: {
            summary: "Payload 1,148 / 1,400 lbs | Fuel 2,940 lbs | Estimated TOW 11,226 / 12,500 lbs",
            plannerPercent: 78,
            plannerDetail: "Planner 78% -> target payload 1,092 lbs | pax 4 | cargo 412 lbs | est TOW 11,170 / 12,500 lbs",
            cargoRows: [
                { name: "Cargo 7 (Nose)", current: "240 lbs", max: "350 lbs" },
                { name: "Cargo 8 (Aft)", current: "172 lbs", max: "300 lbs" },
            ],
            baggageRows: [
                { name: "Baggage 9 (Crew closet)", current: "80 lbs", max: "100 lbs" },
            ],
            seatSummary: "Passenger-loadable seats: 6 | Occupied pax: 4",
            seatRows: [
                { name: "Executive cabin A", current: "2 pax", max: "2 pax" },
                { name: "Executive cabin B", current: "2 pax", max: "4 pax" },
            ],
            resultText: "Payload mismatch previewed to inspect warning state spacing.",
            resultTone: "warning",
        },
    },
    cold_start_enroute: {
        key: "cold_start_enroute",
        label: "Cold Start En Route",
        description: "Cold start has begun. En Route card replaces the three overview cards.",
        defaultSection: "overview",
        status: {
            simconnect_connected: true,
            current_aircraft: "C208B Cargo",
            current_airport: "KJFK",
            airport_match: true,
            aircraft_match: true,
            payload_match: true,
            flight_state: "COLD_START",
            flight_progress: ["Cold start"],
            parked_label: "Parked at KJFK",
            sim_utc_hour: 5,
            sim_utc_minute: 12,
            active_sim_state_label: "Cold Start",
        },
        simconnect: {
            statusText: "SimConnect: Connected",
            statusTone: "success",
            aircraftLine: "Aircraft: C208B Cargo",
            airportLine: "Airport: KJFK",
            gameModeLine: "GameMode: CAREER",
            menuLine: "IsInMenu: false",
            postLine: "EFB POST: warming up state capture",
            connectionLine: "SimConnect timing: connected (waiting 2s)",
        },
        payload: {
            summary: "Payload 820 / 1,250 lbs | Fuel 1,140 lbs | Estimated TOW 6,920 / 8,750 lbs",
            plannerPercent: 72,
            plannerDetail: "Planner 72% -> target payload 900 lbs | pax 0 | cargo 900 lbs | est TOW 7,000 / 8,750 lbs",
            cargoRows: [
                { name: "Cargo 10 (Main deck)", current: "540 lbs", max: "900 lbs" },
                { name: "Cargo 11 (Aft hold)", current: "280 lbs", max: "350 lbs" },
            ],
            baggageRows: [],
            seatSummary: "Passenger-loadable seats: 0 | Occupied pax: 0",
            seatRows: [],
            resultText: "No passengers expected for this cargo setup.",
            resultTone: "info",
        },
    },
    departed: {
        key: "departed",
        label: "Departed",
        description: "In-flight scenario for the panoramic En Route card and long progress chain.",
        defaultSection: "overview",
        status: {
            simconnect_connected: true,
            current_aircraft: "DHC-6-300 Twin Otter Wheels",
            current_airport: "PAJN",
            airport_match: true,
            aircraft_match: true,
            payload_match: true,
            flight_state: "DEPARTED",
            flight_progress: ["Cold start", "Taxi", "Takeoff", "Departed from PAJN"],
            parked_label: "",
            sim_utc_hour: 20,
            sim_utc_minute: 11,
            active_sim_state_label: "In Flight",
        },
        simconnect: {
            statusText: "SimConnect: Connected",
            statusTone: "success",
            aircraftLine: "Aircraft: DHC-6-300 Twin Otter Wheels",
            airportLine: "Airport: PAJN",
            gameModeLine: "GameMode: CAREER",
            menuLine: "IsInMenu: false",
            postLine: "EFB POST: heartbeat sent",
            connectionLine: "SimConnect timing: stable",
        },
        payload: {
            summary: "Payload 1,820 / 2,500 lbs | Fuel 2,310 lbs | Estimated TOW 10,480 / 12,500 lbs",
            plannerPercent: 84,
            plannerDetail: "Planner 84% -> target payload 2,100 lbs | pax 10 | cargo 400 lbs | est TOW 10,760 / 12,500 lbs",
            cargoRows: [
                { name: "Cargo 12 (Nose hold)", current: "160 lbs", max: "250 lbs" },
                { name: "Cargo 13 (Rear hold)", current: "240 lbs", max: "320 lbs" },
            ],
            baggageRows: [
                { name: "Baggage 14 (Cabin bins)", current: "130 lbs", max: "180 lbs" },
            ],
            seatSummary: "Passenger-loadable seats: 14 | Occupied pax: 10",
            seatRows: [
                { name: "Cabin left", current: "5 pax", max: "7 pax" },
                { name: "Cabin right", current: "5 pax", max: "7 pax" },
            ],
            resultText: "Previewed departed state to inspect in-flight readability.",
            resultTone: "info",
        },
    },
    overview_text_density: {
        key: "overview_text_density",
        label: "Overview Text Density",
        description: "Stress test for the square cards with longer copy while keeping the same card geometry.",
        defaultSection: "overview",
        status: {
            simconnect_connected: true,
            current_aircraft: "Pilatus PC-12 NGX",
            current_airport: "NZQN",
            airport_match: false,
            aircraft_match: false,
            payload_match: false,
            required_airport: "NZMF",
            required_aircraft: "C208B Cargo",
            required_payload_lbs: 1134,
            flight_state: "",
            flight_progress: [],
            parked_label: "Parked remote stand at NZQN",
            sim_utc_hour: 7,
            sim_utc_minute: 18,
            active_sim_state_label: "Validation Review",
        },
        overviewCardTextOverrides: {
            airport: "Pilot airport mismatch. Sim reports NZQN while the active job still requires NZMF before departure.",
            aircraft: "Aircraft mismatch. Sim loaded Pilatus PC-12 NGX but the mission requires a configured C208B cargo profile.",
            payload: "Payload mismatch. Cargo and baggage totals are outside the dispatch target and need review before boarding ends.",
        },
        simconnect: {
            statusText: "SimConnect: Connected",
            statusTone: "success",
            aircraftLine: "Aircraft: Pilatus PC-12 NGX",
            airportLine: "Airport: NZQN",
            gameModeLine: "GameMode: CAREER",
            menuLine: "IsInMenu: false",
            postLine: "EFB POST: ready",
            connectionLine: "SimConnect timing: stable",
        },
        payload: {
            summary: "Payload 1,040 / 1,400 lbs | Fuel 1,880 lbs | Estimated TOW 9,180 / 10,450 lbs",
            plannerPercent: 81,
            plannerDetail: "Planner 81% -> target payload 1,134 lbs | pax 6 | cargo 294 lbs | est TOW 9,274 / 10,450 lbs",
            cargoRows: [
                { name: "Cargo 6 (Rear bay)", current: "154 lbs", max: "250 lbs" },
                { name: "Cargo 7 (Cabin floor)", current: "140 lbs", max: "220 lbs" },
            ],
            baggageRows: [
                { name: "Baggage 8 (Wardrobe)", current: "76 lbs", max: "120 lbs" },
            ],
            seatSummary: "Passenger-loadable seats: 8 | Occupied pax: 6",
            seatRows: [
                { name: "Executive seats", current: "4 pax", max: "6 pax" },
                { name: "Club seats", current: "2 pax", max: "2 pax" },
            ],
            resultText: "Long-copy preview is active to validate text containment and card safe areas.",
            resultTone: "warning",
        },
    },
    payload_busy: {
        key: "payload_busy",
        label: "Payload Busy",
        description: "Dense payload editing state to inspect list readability and spacing.",
        defaultSection: "payload",
        status: {
            simconnect_connected: true,
            current_aircraft: "737 Max 8 Passengers",
            current_airport: "EGLL",
            airport_match: true,
            aircraft_match: true,
            payload_match: false,
            required_payload_lbs: 16368,
            flight_state: "",
            flight_progress: [],
            parked_label: "Parked at EGLL",
            sim_utc_hour: 12,
            sim_utc_minute: 28,
            active_sim_state_label: "Boarding",
        },
        simconnect: {
            statusText: "SimConnect: Connected",
            statusTone: "success",
            aircraftLine: "Aircraft: 737 Max 8 Passengers",
            airportLine: "Airport: EGLL",
            gameModeLine: "GameMode: FREE FLIGHT",
            menuLine: "IsInMenu: false",
            postLine: "EFB POST: ready",
            connectionLine: "SimConnect timing: stable",
        },
        payload: {
            summary: "Payload 15,440 / 18,600 lbs | Fuel 22,900 lbs | Estimated TOW 144,820 / 181,200 lbs",
            plannerPercent: 88,
            plannerDetail: "Planner 88% -> target payload 16,368 lbs | pax 128 | cargo 3,568 lbs | est TOW 145,748 / 181,200 lbs",
            cargoRows: [
                { name: "Cargo 1 (Forward hold)", current: "1,260 lbs", max: "2,000 lbs" },
                { name: "Cargo 2 (Aft hold)", current: "1,180 lbs", max: "2,000 lbs" },
                { name: "Cargo 3 (Bulk)", current: "1,128 lbs", max: "1,500 lbs" },
            ],
            baggageRows: [
                { name: "Baggage 4 (Crew)", current: "220 lbs", max: "300 lbs" },
                { name: "Baggage 5 (Cabin reserve)", current: "160 lbs", max: "250 lbs" },
            ],
            seatSummary: "Passenger-loadable seats: 162 | Occupied pax: 128",
            seatRows: [
                { name: "Economy forward", current: "48 pax", max: "54 pax" },
                { name: "Economy mid", current: "46 pax", max: "54 pax" },
                { name: "Economy aft", current: "34 pax", max: "42 pax" },
            ],
            resultText: "Payload sync preview only. Buttons are intentionally non-destructive.",
            resultTone: "warning",
        },
    },
    simconnect_error: {
        key: "simconnect_error",
        label: "SimConnect Error",
        description: "Disconnected server and stale post state for debug surface checks.",
        defaultSection: "simconnect",
        status: {
            simconnect_connected: false,
            current_aircraft: "",
            current_airport: "",
            airport_match: false,
            aircraft_match: false,
            payload_match: false,
            flight_state: "",
            flight_progress: [],
            parked_label: "",
            sim_utc_hour: null,
            sim_utc_minute: null,
            active_sim_state_label: "Unknown",
        },
        simconnect: {
            statusText: "SimConnect: Disconnected",
            statusTone: "danger",
            aircraftLine: "Aircraft: unavailable",
            airportLine: "Airport: unavailable",
            gameModeLine: "GameMode: (manager missing)",
            menuLine: "IsInMenu: (manager missing)",
            postLine: "EFB POST: FAILED",
            connectionLine: "SimConnect timing: disconnected",
        },
        payload: {
            summary: "Payload planner unavailable while the addon connection is offline.",
            plannerPercent: 0,
            plannerDetail: "No live Mass & Balance data. Use this scenario only for layout and warning colors.",
            cargoRows: [],
            baggageRows: [],
            seatSummary: "Passenger-loadable seats: 0 | Occupied pax: 0",
            seatRows: [],
            resultText: "Addon server is unreachable.",
            resultTone: "danger",
        },
    },
};
